name: busha_assessment
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.0
  logger: ^2.2.0
  dio: ^5.4.3+1
  contra: ^0.0.2
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  responsive_grid_list: ^1.4.0
  url_launcher: ^6.2.6
  fluttertoast: ^8.2.5

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  test: ^1.24.9

flutter:
  uses-material-design: true

  assets:
    - assets/pngs/
    - assets/svgs/
